# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production

baseurl = "https://azukibar-test.netlify.app/"  # Include trailing slash
title = "„Ç¢„Ç§„Çπ„ÅÆÊ£í"
author = "Azuki-bar"
copyright = "Copyright ¬© 2021, Azuki-bar; all rights reserved."
# canonifyurls = true
paginate = 5
theme = "hugo-clarity"
isCJKLanguage = true

canonifyurls = true

disqusShortname = ""

DefaultContentLanguage = "jp"

# [languages]
# config/_default/languages.toml
#
# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true # change to false to disable inclusion of rawHTML and math functions
      xhtml = false
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = -100

  [[menu.main]]
    identifier = "about"
    name = "about"
    # pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 0
    [menu.main.params]
      class = "highlight-menu-item"


  [[menu.main]]
    identifier = "Link"
    name = "Link"
    url = "link"
    weight = -100


[permalinks]
  blog = "/blog/:year/:month/:title/"

[params]
author = "„ÅÇ„Åö„Åç„Éê„Éº"
twitter = "@azukibar_D"
largeTwitterCard = true # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "ÈõªÊ∞ó„ÅßÈÄö‰ø°„Åô„ÇãÂ§ßÂ≠¶„Å´„ÅÑ„ÇãÂ≠¶Áîü„ÅÆ„Çµ„Ç§„Éà„ÄÇ<br>Ë©≥„Åó„Åè„ÅØ‰∏ã„ÅÆ„Éú„Çø„É≥„Åß„Å©„ÅÜ„Åû„ÄÇ"
# since = 2021

introURL = "about/" # set the url for the 'read more' button below the introDescription, or set to false to not show the button
# description = "" # set your site's description here. will be use for home page content meta tags (seo). Alternatively set this description in your homepage content file i.e content/_index.md. Whatever is set in the latter will take precedence

# showShare = false # Uncomment to not show share buttons on each post. Also available in each post's front matter.

# Google analytics Id
ga_analytics = "XXXXXXXXXX"

# Baidu analytics Id
# baidu_analytics = "XXXXXXXX"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png"

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = true

# enable math notation. Switch to `true` to enable mathjax in your site.
enableMathNotation = true

# directory(s) where your articles are located
mainSections = ["about", "post", "blog"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

# logo = "logos/logo.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

# some site owners want to decide how they would like their sites to be introduced users. These settings give you as a site owner to decide how the user will view your site for the first time.

# please note that you cannot enforce both modes at the same time. i.e by enforcing one mode, you priotise it over the other (by setting it to true). enforceDarkMode will be commented out

# please also not that mode toggle UI will remain in place. That way, if a user prefers darkmode, they can have their way.

enforceLightMode = false
# enforceDarkMode = false

# customize footer icon. see issue https://github.com/chipzoller/hugo-clarity/issues/77
# footerLogo = "icons/copy.svg"

# Text for the languages menu.
languageMenuName = "üåê"

# Title separator, default to |.
# titleSeparator = "|"

# Enable or disable comment globally. Default to true.
# comment = false

# Maximum number of recent posts.
# numberOfRecentPosts = 8

# Maximum number of featured posts.
# numberOfFeaturedPosts = 8

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
dateFormat = "2006-01-02" # Default to "Jan 2, 2006".
# customFonts = false # toggle to true if you want to use custom fonts only.

# The year when ths website was created, this value is used in the copyright
# notice of the footer.
# since = 2016
include_toc = true
